theme: jekyll-theme-hacker
title: OliverMakesGames
description: chill indie game dev
github:
  is_project_page: false

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
